### ISSUE TITLE
Issue Function Test

### ISSUE THREAD

**Issue by jkimpro** [okjcd123/OSS12#1]
Due on May 5

**Comment by EIdeallab** [comment]
전부 주석을 달고 난 뒤에는 주석 양식을 통일합시다.

**Comment by jkimpro** [comment]
주석 양식의 경우 영어로 할지, 한국어로 할지의 여부 등은
5월17일 수업이후 5월18일 회의 때 결정합시다.

**Comment by jkimpro** [comment]
Test Complete
